# import packages

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

# import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Loading data

In [2]:
df = pd.read_csv('/kaggle/input/zomato-dataset/zomato.csv')
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

# Grtting df information

In [3]:
df.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [4]:
df.describe()

              votes
count  51717.000000
mean     283.697527
std      803.838853
min        0.000000
25%        7.000000
50%       41.000000
75%      198.000000
max    16832.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  object
 13  reviews_list                 51717 non-null  object
 14  menu_item                    51717 non-null  object
 15  listed_in(type)              51717 non-null  object
 16  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(16)
memory usage: 6.7+ MB

In [6]:
df.shape

(51717, 17)

In [7]:
df.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [8]:
df = df.drop(['url','address','phone','menu_item','reviews_list','dish_liked'],axis=1)
df.shape

(51717, 11)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         51717 non-null  object
 1   online_order                 51717 non-null  object
 2   book_table                   51717 non-null  object
 3   rate                         43942 non-null  object
 4   votes                        51717 non-null  int64
 5   location                     51696 non-null  object
 6   rest_type                    51490 non-null  object
 7   cuisines                     51672 non-null  object
 8   approx_cost(for two people)  51371 non-null  object
 9   listed_in(type)              51717 non-null  object
 10  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(10)
memory usage: 4.3+ MB

In [10]:
df.drop_duplicates(inplace=True)
df.shape

(51609, 11)

# Handle rate col

In [ ]:
df['rate'].unique()

In [ ]:
def handrate(V):
    if (V == 'NEW' or V =='-'):
        return np.nan
    else:
        V = str(V).split('/')[0]
        return float(V)

In [ ]:
df['rate'] = df['rate'].apply(handrate)
df['rate'].head()

In [ ]:
df['rate'].unique()

In [ ]:
df['rate'].isna().sum()

In [ ]:
df['rate'].fillna(df['rate'].median(), inplace=True)
df['rate'].isna().sum()

In [ ]:
df.dropna(inplace =True)
df.head()

In [ ]:
df.shape

In [ ]:
df['location'].unique()

In [ ]:
df['listed_in(city)'].unique()

In [ ]:
df.drop(['listed_in(city)'],axis=1)
df.head()

In [ ]:
df['approx_cost(for two people)'].unique()

# Handle comma col

In [ ]:
def handcomma(v):
    v = str(v)
    if ',' in v:
        v=v.replace(',','')
        return float(v)
    else:
        return float(v)

In [ ]:
df['approx_cost(for two people)'] = df['approx_cost(for two people)'].apply(handcomma)
df['approx_cost(for two people)'].unique()

In [ ]:
df['approx_cost(for two people)'].isna().sum()

# Handle rest_type col

In [ ]:
df['rest_type'].value_counts()

In [ ]:
rest_type =df['rest_type'].value_counts(ascending=False)
rest_type

In [ ]:
other = rest_type[rest_type<1000]
other

In [ ]:
def handle_rest_type(value):
    if value in other:
        return 'other'
    else:
        return value

In [ ]:
df['rest_type'] = df['rest_type'].apply(handle_rest_type)
df['rest_type'].value_counts()

# Handle Location col

In [ ]:
location = df['location'].value_counts(ascending=False)
loc300 = location[location<390]

In [ ]:
def handloc(v):
    if(v in loc300 ):
        return 'other'
    else:
        return v

In [ ]:
df['location'] =df['location'].apply(handloc)
df['location'].value_counts(ascending=False)

# Handle cuisines col

In [ ]:
cuisines = df['cuisines'].value_counts(ascending=False)
cuisines100 = cuisines[cuisines<100]

In [ ]:
def handcusi(v):
    if (v in cuisines100):
        return 'other'
    else:
        return v

In [ ]:
df['cuisines'] = df['cuisines'].apply(handcusi)
df['cuisines'].value_counts(ascending=False)

In [ ]:
df.info()

In [ ]:
df.head()

In [ ]:
df.shape

In [ ]:
df.drop(['name'],axis=1)

In [ ]:
df['approx_cost(for two people)']

In [ ]:
num_cols = list(df.select_dtypes(exclude='object').columns)
num_cols.remove('approx_cost(for two people)')
num_cols

In [ ]:
cat_cols = list(df.select_dtypes(include='object').columns)
cat_cols.remove('name')
cat_cols.remove('listed_in(city)')
cat_cols

# Filling missing values

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False,handle_unknown="ignore")
ohe.fit(df[cat_cols])

In [ ]:
new_cols = list(ohe.get_feature_names())
new_cols

In [ ]:
len(new_cols)

In [ ]:
df[new_cols] = ohe.transform(df[cat_cols])

In [ ]:
df.head()

# feature reduction on corr

In [ ]:
final_col=list(df.corr()['approx_cost(for two people)'][(df.corr()['approx_cost(for two people)']>=0.05)|(df.corr()['approx_cost(for two people)']<=-0.05)].index)

In [ ]:
df.corr()['approx_cost(for two people)'].tail(10)

In [ ]:
df[final_col]

In [ ]:
final_col.remove('approx_cost(for two people)')

# Find X and Y col

In [ ]:
X = df[final_col]
y= df['approx_cost(for two people)']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.25,random_state=17)

In [ ]:
##############################################################################################################################################################3

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

In [ ]:
# dict1 = {'min_samples_leaf' : [2,3,4],
#          'max_depth' : [2,3,4],
#         'n_estimators': [500,1000,1500]}

In [ ]:
# grid_cv = GridSearchCV(RandomForestRegressor(), param_grid=dict1, cv=5, verbose=2)
# grid_cv.fit(X_train,y_train)

In [ ]:
# import pickle

In [ ]:
#pickle.dump(grid_cv, open('rf_model.h5','wb'))

In [ ]:
#grid_cv.score(X_test,y_test)

# Model RandomForest

In [ ]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()

In [ ]:
model.fit(X_train,y_train)

In [ ]:
model.score(X_test,y_test)

# Model Ada

In [ ]:
from sklearn.neighbors import KNeighborsRegressor()
model = KNeighborsRegressor()

In [ ]:
model.fit(X_train,y_train)

In [ ]:
model.score(X_test,y_test)

# Model DT

In [ ]:
from sklearn.tree import DecisionTreeRegressor

In [ ]:
model = DecisionTreeRegressor()
model.fit(X_train,y_train)

In [ ]:
model.score(X_test,y_test)